<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <UseWindowsForms>true</UseWindowsForms>
    <ImplicitUsings>enable</ImplicitUsings>
    <AssemblyName>TatoVPN</AssemblyName>
    <RootNamespace>miVPN</RootNamespace>
    <ApplicationIcon>Assets\app.ico</ApplicationIcon>
    <Title>TatoVPN</Title>
    <Product>TatoVPN</Product>
  </PropertyGroup>

  <ItemGroup>
    <Content Include="Assets\**">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="SSH.NET" Version="2026.0.0" />
    <PackageReference Include="System.Management" Version="8.0.0" />
  </ItemGroup>

</Project>